name: 打包文件并推送到云服务器
# 监听 main 分支上的 push 事件
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    # 构建环境使用 ubuntu
    runs-on: ubuntu-latest
    steps:
      # 官方action, 将代码拉取到虚拟机
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 安装node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      # 全局安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 下载依赖、打包项目
      - name: Install and Build
        run: |
          pnpm install
          pnpm run build

      # 清空目标服务器上的目录内容
      - name: Clear Target Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf /nwa/nginx/html/mytool/*
      # 部署到服务器
      - name: Upload to Deploy Server
        uses: appleboy/scp-action@master
        with:
          # 服务器域名
          host: ${{ secrets.SSH_HOST }}
          # 服务器用户名
          username: ${{ secrets.SSH_USERNAME }}
          # 服务器密码
          password: ${{ secrets.SSH_PASSWORD }}
          # 服务器端口
          port: ${{ secrets.SSH_PORT }}
          # 指定上传的文件目录(项目配置的打包目录名称)
          source: './dist/*'
          # 指定上传服务器目录
          target: '/nwa/nginx/html/mytool'
          # 解压时覆盖现有文件
          overwrite: true
          # 删除指定数量的前导路径元素
          strip_components: 1
